---
galaxy_info:
  author: Ted Cook
  description: An Ansible role to install and configure git
  license: MIT
  min_ansible_version: 2.2
  platforms:
    - name: EL
      versions:
        - 7
    - name: Archlinux
      versions:
        - all
    - name: Ubuntu
      versions:
        - bionic
        - xenial
    - name: Debian
      versions:
        - stretch

  galaxy_tags:
    - git

dependencies: []
