---
- name: include variable overrides
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
      skip: true

- name: install packages
  package:
    name: "{{ git_packages | default(git_packages_default) }}"
    state: "{{ git_packages_state }}"
  become: yes

- name: execute lfs auto install command
  shell: "curl -s {{ git_lfs_install_url }} | bash"
  args:
    warn: false
  changed_when: false
  when: git_lfs
  tags:
    - skip_ansible_lint

- name: install git-lfs yum package
  yum:
    name: "{{ git_packages_lfs }}"
    state: "{{ git_packages_state }}"
    update_cache: yes
  when:
    - git_lfs
    - ansible_os_family == 'RedHat'
  notify: initialize git-lfs

- name: install git-lfs apt package
  apt:
    name: "{{ git_packages_lfs }}"
    state: "{{ git_packages_state }}"
    update_cache: yes
  when:
    - git_lfs
    - ansible_os_family == 'Debian'
  notify: initialize git-lfs

- name: set up git prompt
  copy:
    dest: "~/{{ git_prompt_path }}"
    src: "{{ git_prompt_template }}"
  when: git_configure
  no_log: yes

- name: configure git prompt
  lineinfile:
    dest: "~/{{ bash_configuration_file }}"
    line: '[[ -f ~/{{ git_prompt_path }} ]] && source ~/{{ git_prompt_path }}'
    create: yes
  when: git_configure

- name: set up git completion
  copy:
    dest: "~/{{ git_completion_path }}"
    src: "{{ git_completion_template }}"
  no_log: yes
  when: git_configure

- name: configure git completion
  lineinfile:
    dest: "~/{{ bash_configuration_file }}"
    line: '[[ -f ~/{{ git_completion_path }} ]] && source ~/{{ git_completion_path }}'
    create: yes
  when: git_configure
